name: soccer_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.2.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  appsflyer_sdk: ^6.12.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  share_plus:
  flutter_inappwebview: ^5.7.2+3
  firebase_remote_config: ^4.3.17
  firebase_core: ^2.27.0
  url_launcher:
  app_tracking_transparency: ^2.0.4
  overlay_support: ^2.1.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # dio: ^5.6.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/puzzle/
  fonts:
    - family: SFR
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SFUIText-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SFUIText-Bold.ttf